
services:

  postgresql:
    container_name: "${PROJECT_ALIAS}_postgresql"
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: svallotale
      POSTGRES_PASSWORD: svallotale
      POSTGRES_DB: database
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
